const router = require("express").Router();
const auth = require("../../common/middleware/auth.middleware");
const requireRole = require("../../common/middleware/requireRole");
const validate = require("../../common/middleware/validate.middleware");
const wrap = require("../../common/utils/asyncHandler");
const c = require("./user.controller");
const v = require("./user.validator");
router.use(auth, requireRole("super_admin"));
router.post("/", validate(v.createUserValidation), wrap(c.createUser));
router.get("/", validate(v.listUsersValidation), wrap(c.listUsers));
router.get("/:userId", validate(v.userIdValidation), wrap(c.getUserById));
router.patch("/:userId/verify", validate(v.verifyUserValidation), wrap(c.verifyUser));
router.patch("/:userId/role", validate(v.updateUserRoleValidation), wrap(c.updateUserRole));
router.patch("/:userId/status", validate(v.updateUserStatusValidation), wrap(c.updateUserStatus));
module.exports = router;
